### ISSUE TITLE
admin for this repo

### ISSUE THREAD

**Issue by pdimens** [BioJulia/PopGen.jl_archive#11]
@BenJWard 
May I please get admin rights to this repo? I need to generate the SSH key for doc building, clean up the branches/defaults, etc. to finish migrating my fork into BioJulia.

**Comment by pdimens** [comment]
@BenJWard, I'm trying to make BioJulia/PopGen.jl the source of the releases, etc. I would also like the documentation to be built and hosted off of BioJulia.net rather than pdimens.github.io. How can we shore up this merge back to Biojulia so the development/release isn't happening from my fork anymore?

**Comment by pdimens** [comment]
@BenJWard can I just transfer over the entirety of my fork into BioJulia as Mose suggests here? https://github.com/JuliaRegistries/General/pull/31669#issuecomment-796222625

**Comment by kescobo** [comment]
I think @jakobnissen can help too, and is a bit more active

**Comment by pdimens** [comment]
@jakobnissen Can we do https://github.com/JuliaRegistries/General/pull/31669#issuecomment-796252515 as was suggested by Mose?

**Comment by jakobnissen** [comment]
@pdimens I've given you admin right to this repository. I think that's only right, since you're the main developer.
Edit: With admin right, you can do the transfer, right?
